FROM openjdk:8-alpine

ARG JAR_FILE=flyway-showcase-runner.jar
COPY target/${JAR_FILE} /opt/application.jar

ENV JAVA_OPTS="-Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true"
ENV QUARKUS_OPTS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"

EXPOSE 8080
ENTRYPOINT exec java $JAVA_OPTS $QUARKUS_OPTS -jar /opt/application.jar